Added default shard size setting
groveco/django-sprinklers pull request #7
Opened 2019-07-31 15:19 UTC by Anton-Shutik

Added default shard size config

2019-07-31 15:30 UTC, al-the-x requested changes

2019-07-31 15:30 UTC, al-the-x commented on sprinklers/app_settings.py
> +SPRINKLER_DEFAULT_SHARD_SIZE = getattr(settings, 'SPRINKLER_DEFAULT_SHARD_SIZE', 20000)
Settings `import`-ed where?

2019-07-31 15:30 UTC, al-the-x commented on sprinklers/base.py
> +    shard_size = app_settings.SPRINKLER_DEFAULT_SHARD_SIZE
Same for `app_settings`...?

2019-08-02 14:43 UTC, al-the-x commented on sprinklers/base.py
> +import app_settings
Use relative imports for clarity:
```suggestion
from . import app_settings
```

2019-08-02 16:34 UTC, al-the-x commented
Can you link to the PR in `groveco/grove` that integrates this?

2019-08-05 07:02 UTC, Anton-Shutik commented
@al-the-x https://github.com/groveco/grove/pull/7108 It's draft PR, because this code is not merged into main repo

2019-08-06 21:05 UTC, al-the-x approved these changes

2019-08-15 08:43 UTC, merged